[package]
name = "nebula_core"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
godot = { version = "0.4.4", features = ["register-docs"] }
regex = "1.12.2"
aes = "0.8"
cbc = "0.1"
hex = "0.4"